### ISSUE TITLE
Bad heading, plane stuck @ 0 deg

### ISSUE THREAD

**Issue by toorop** [toorop/FsBlackBox#1]
![@genesis](https://user-images.githubusercontent.com/514704/99629014-9a95ab80-2a37-11eb-9b19-fb4ffc0a25df.png)
![6N9VNu9r0S](https://user-images.githubusercontent.com/514704/99629087-b13c0280-2a37-11eb-82ec-1e55dff740cb.png)

**Comment by kappuccino** [comment]
je vais trouver le stagiaire responsable et lui en parler !

**Comment by toorop** [comment]
![](https://media4.giphy.com/media/SV03XkNPDE28NISRGw/giphy.gif)
Visiblement tu as fait ce qu'il fallait je ferme.
